# Generated by Django 5.1.1 on 2024-09-19 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relembrario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='lembrancas',
            name='data_criacao',
            field=models.DateTimeField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lembrancas',
            name='data_evento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lembrancas',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lembrancas',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lembrancas',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_lembrancas/'),
        ),
        migrations.AddField(
            model_name='lembrancas',
            name='local',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lembrancas',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lembrancas',
            name='tags',
            field=models.ManyToManyField(blank=True, to='relembrario.tag'),
        ),
    ]
